apiVersion: apps/v1
kind: Deployment
metadata:
  name: langflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langflow
  template:
    metadata:
      labels:
        app: langflow
    spec:
      containers:
      - name: langflow
        image: docker_image:latest  # Replace with your Docker image name and tag
        ports:
        - containerPort: 5000
      - name: mongo
        image: mongo:latest  
        ports:
        - containerPort: 27017  # 
